### ISSUE TITLE
Will this be packaged and part of the antergos repository?

### ISSUE THREAD

**Issue by searedvandal** [Antergos/antergos-alpm-hooks#3]
Will this hook be part of the antergos repo, so that updates won't make the system report as Arch after update of the filesystem package?

Fresh install before I forced a reinstall of 'filesystem':
```
searedvandal-> cat /etc/os-release 
NAME="Antergos Linux"
VERSION="18.6-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:18.6"
ANSI_COLOR="1;34;40"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
```

After:
```
searedvandal-> cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

Would be nice to not having to add this manually for people who want their system to report correctly :)

**Comment by eli-schwartz** [comment]
The package is currently in the repos and installed as part of the "antergos-base" group, so I assume this is fixed at least on new installs, right?

**Comment by lots0logs** [comment]
Its now installed as a dependency of **antergos-mirrorlist** thus all antergos systems that have installed latest updates now have this package.
